### ISSUE TITLE
Make technologies a checklist

### ISSUE THREAD

**Issue by ashwilliams15** [ashwilliams15/job-hunter#1]
- [x]  Once checked, they disappear
- [x] After being checked, they show up on learned technologies list
- [x] When checked, a popup appears to remind me to add this new technology to my resume
